import Head from "next/head"
import { Fragment } from "react/cjs/react.production.min"

export default function AppLayout ({children,title}) {

    return (<Fragment>
        <Head>
          <title>{title}</title>
          <meta name="Timeline" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            {children}
        </main>
        
        <style jsx global>{`
        html,
        body {
            padding: 0;
            margin: 0;
            font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
            Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
        }

        a {
            color: inherit;
            text-decoration: none;
        }

        * {
            box-sizing: border-box;
        }

        .container {
            padding: 0 2rem;
        }

        .main {
            min-height: 100vh;
            padding: 4rem 0;
            flex: 1;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        } 
    `}</style>
    </Fragment>)
}