import Head from "next/head"

import { Fragment } from "react/cjs/react.production.min"

import style, { gobalStyle } from "./style"




export default function AppLayout ({children,title}) {

    return (<Fragment>
        <Head>
          <title>{title}</title>
          <meta name="Timeline" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
            <main>
                {children}
            </main>
        </div>
        
        <style jsx >{style}</style>
        <style jsx global>{gobalStyle}</style>
    </Fragment>)
}